# GitHub Actions for MicrotonalAudioKit: includes builds, tests and releases
name: CI

on: [push, pull_request]
env:
  XCODE_VER: latest-stable

jobs:
  # Generate Wiki docs 
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out MicrotonalAudioKit
        uses: actions/checkout@v2
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          module-name: MicrotonalAudioKit
          output: "Documentation"
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "Documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

